version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cobranca
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql